/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package railpilot;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Sanjula
 */
public class AdminHome extends javax.swing.JFrame {

    /**
     * Creates new form PassengerHome
     */
    public AdminHome() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    public void setColor(JPanel p)
    {
        p.setBackground(new Color(0,206,209));
    }
        public void resetColor(JPanel pl)
    {
        pl.setBackground(new Color(0,255,255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addtrain = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        deletetrain = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        report = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(576, 399));
        setMinimumSize(new java.awt.Dimension(576, 399));
        setPreferredSize(new java.awt.Dimension(576, 399));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        addtrain.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        addtrain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addtrain.setText("ADD TRAIN");
        addtrain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtrainMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addtrainMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addtrainMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addtrain, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addtrain, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jPanel6.setBackground(new java.awt.Color(0, 255, 255));

        deletetrain.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        deletetrain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deletetrain.setText("DELETE TRAIN");
        deletetrain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletetrainMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deletetrainMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deletetrainMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deletetrain, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deletetrain, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, -1));

        jPanel8.setBackground(new java.awt.Color(0, 255, 255));

        report.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        report.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        report.setText("CUSTOMER REPORTS");
        report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(report, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(report, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sanjula\\Downloads\\Untitled design (12).png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 580, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addtrainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addtrainMouseEntered
        setColor(jPanel1);
    }//GEN-LAST:event_addtrainMouseEntered

    private void addtrainMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addtrainMouseExited
        resetColor(jPanel1);
    }//GEN-LAST:event_addtrainMouseExited

    private void deletetrainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletetrainMouseEntered
        setColor(jPanel6);
    }//GEN-LAST:event_deletetrainMouseEntered

    private void deletetrainMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletetrainMouseExited
        resetColor(jPanel6);
    }//GEN-LAST:event_deletetrainMouseExited

    private void reportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportMouseEntered
        setColor(jPanel8);
    }//GEN-LAST:event_reportMouseEntered

    private void reportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportMouseExited
        resetColor(jPanel8);
    }//GEN-LAST:event_reportMouseExited

    private void addtrainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addtrainMouseClicked
        AddTrain obj = new AddTrain();
        obj.setVisible(true);
    }//GEN-LAST:event_addtrainMouseClicked

    private void deletetrainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletetrainMouseClicked
        traindelete obj = new traindelete();
        obj.setVisible(true);
    }//GEN-LAST:event_deletetrainMouseClicked

    private void reportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportMouseClicked
        FinalReport obj = new FinalReport();
        obj.setVisible(true);
    }//GEN-LAST:event_reportMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addtrain;
    private javax.swing.JLabel deletetrain;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel report;
    // End of variables declaration//GEN-END:variables
}
