/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package railpilot;

import java.awt.Color;
import javax.swing.*;
import java.sql.Connection;
import java.sql.DriverManager;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Sanjula
 */
public class FinalReport extends javax.swing.JFrame {

    /**
     * Creates new form FinalReport
     */
    public FinalReport() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        fromcombobox.setSelectedIndex(-1);
        tocombobox.setSelectedIndex(-1);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        fromcombobox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        tocombobox = new javax.swing.JComboBox<>();
        btn_search = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("From:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, 20));

        fromcombobox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fromcombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anuradhapura", "Kandy", "Colombo", "Bambalapitiya", "Galle", "Matara" }));
        fromcombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromcomboboxActionPerformed(evt);
            }
        });
        getContentPane().add(fromcombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 220, 30));

        jLabel5.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("To:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 40, 20));

        tocombobox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tocombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anuradhapura", "Kandy", "Colombo", "Bambalapitiya", "Galle", "Matara" }));
        tocombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tocomboboxActionPerformed(evt);
            }
        });
        getContentPane().add(tocombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 220, 30));

        btn_search.setBackground(new java.awt.Color(0, 255, 255));
        btn_search.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        btn_search.setText("SEARCH");
        btn_search.setBorder(null);
        btn_search.setBorderPainted(false);
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        getContentPane().add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 210, 30));

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setText("CUSTOMER REPORTS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 380, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sanjula\\Downloads\\Untitled design (15).png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fromcomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromcomboboxActionPerformed
        tocombobox.setSelectedIndex(-1);
    }//GEN-LAST:event_fromcomboboxActionPerformed

    private void tocomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tocomboboxActionPerformed
        
    }//GEN-LAST:event_tocomboboxActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
     String selectedDeparture = (String) fromcombobox.getSelectedItem();
    String selectedDestination = (String) tocombobox.getSelectedItem();
    
    if (selectedDeparture == null || selectedDeparture.isEmpty() || selectedDestination == null || selectedDestination.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select both departure and destination.", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
    }
    try{
    JasperDesign jasperdesign1 = net.sf.jasperreports.engine.xml.JRXmlLoader.load("C:\\Users\\Sanjula\\Documents\\NetBeansProjects\\Railpilot\\src\\railpilot\\FinalReport.jrxml");
    JRDesignQuery designquery1 = new JRDesignQuery();
    
    designquery1.setText("SELECT * FROM passenger WHERE Departure = '" + selectedDeparture + "' AND Destination = '" + selectedDestination + "'");
    jasperdesign1.setQuery(designquery1);
    JasperReport jasperreport1 = JasperCompileManager.compileReport(jasperdesign1);
    String dbpath = "jdbc:mysql://localhost/railpilot";
   
    Connection con= DriverManager.getConnection(dbpath,"root","");
    JasperPrint jasperprint1=JasperFillManager.fillReport(jasperreport1,null,con);
    JasperViewer.viewReport(jasperprint1);
    }
        
        catch(Exception e) {
    e.printStackTrace(); // Print the full stack trace for debugging
    JOptionPane.showMessageDialog(this, "Error generating report: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}           
    }//GEN-LAST:event_btn_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinalReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_search;
    private javax.swing.JComboBox<String> fromcombobox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> tocombobox;
    // End of variables declaration//GEN-END:variables
}
