/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package railpilot;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Sanjula
 */
public class PassengerHome extends javax.swing.JFrame {

    /**
     * Creates new form PassengerHome
     */
    public PassengerHome() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    public void setColor(JPanel p)
    {
        p.setBackground(new Color(0,206,209));
    }
        public void resetColor(JPanel pl)
    {
        pl.setBackground(new Color(0,255,255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        booktkt = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        deletetkt = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        updatetkt = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        viewtkt = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        receipt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(584, 414));
        setMinimumSize(new java.awt.Dimension(584, 414));
        setPreferredSize(new java.awt.Dimension(584, 414));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        booktkt.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        booktkt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        booktkt.setText("BOOK TICKET");
        booktkt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                booktktMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                booktktMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                booktktMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(booktkt, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(booktkt, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 43, -1, -1));

        jPanel4.setBackground(new java.awt.Color(0, 255, 255));

        deletetkt.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        deletetkt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deletetkt.setText("DELETE TICKET");
        deletetkt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletetktMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deletetktMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deletetktMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deletetkt, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deletetkt, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jPanel6.setBackground(new java.awt.Color(0, 255, 255));

        updatetkt.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        updatetkt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        updatetkt.setText("UPDATE TICKET");
        updatetkt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updatetktMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updatetktMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updatetktMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(updatetkt, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(updatetkt, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, -1));

        jPanel7.setBackground(new java.awt.Color(0, 255, 255));

        viewtkt.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        viewtkt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewtkt.setText("VIEW TICKET");
        viewtkt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewtktMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewtktMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewtktMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewtkt, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(viewtkt, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, -1));

        jPanel8.setBackground(new java.awt.Color(0, 255, 255));

        receipt.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        receipt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        receipt.setText("GENERATE RECIEPT");
        receipt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                receiptMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                receiptMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                receiptMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(receipt, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(receipt, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sanjula\\Downloads\\Untitled design (12).png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 590, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void booktktMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booktktMouseEntered
        setColor(jPanel1);
    }//GEN-LAST:event_booktktMouseEntered

    private void booktktMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booktktMouseExited
        resetColor(jPanel1);
    }//GEN-LAST:event_booktktMouseExited

    private void deletetktMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletetktMouseEntered
        setColor(jPanel4);
    }//GEN-LAST:event_deletetktMouseEntered

    private void deletetktMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletetktMouseExited
        resetColor(jPanel4);
    }//GEN-LAST:event_deletetktMouseExited

    private void updatetktMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatetktMouseEntered
        setColor(jPanel6);
    }//GEN-LAST:event_updatetktMouseEntered

    private void updatetktMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatetktMouseExited
        resetColor(jPanel6);
    }//GEN-LAST:event_updatetktMouseExited

    private void viewtktMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewtktMouseEntered
        setColor(jPanel7);
    }//GEN-LAST:event_viewtktMouseEntered

    private void viewtktMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewtktMouseExited
        resetColor(jPanel7);
    }//GEN-LAST:event_viewtktMouseExited

    private void receiptMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_receiptMouseEntered
        setColor(jPanel8);
    }//GEN-LAST:event_receiptMouseEntered

    private void receiptMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_receiptMouseExited
        resetColor(jPanel8);
    }//GEN-LAST:event_receiptMouseExited

    private void booktktMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booktktMouseClicked
        ticketbooking1 obj = new ticketbooking1();
        obj.setVisible(true);
    }//GEN-LAST:event_booktktMouseClicked

    private void updatetktMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatetktMouseClicked
        ticketupdate obj = new ticketupdate();
        obj.setVisible(true);
    }//GEN-LAST:event_updatetktMouseClicked

    private void deletetktMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletetktMouseClicked
        ticketdelete obj = new ticketdelete();
        obj.setVisible(true);
    }//GEN-LAST:event_deletetktMouseClicked

    private void viewtktMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewtktMouseClicked
        PassengerView obj = new PassengerView();
        obj.setVisible(true);
    }//GEN-LAST:event_viewtktMouseClicked

    private void receiptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_receiptMouseClicked
        ViewReceipt obj = new ViewReceipt();
        obj.setVisible(true);
    }//GEN-LAST:event_receiptMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PassengerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PassengerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PassengerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PassengerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PassengerHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel booktkt;
    private javax.swing.JLabel deletetkt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel receipt;
    private javax.swing.JLabel updatetkt;
    private javax.swing.JLabel viewtkt;
    // End of variables declaration//GEN-END:variables
}
