/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package railpilot;

import java.awt.Color;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.*;
import java.util.regex.Matcher; 
import java.util.regex.Pattern; 
import java.awt.Window;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.*;



/**
 *
 * @author Sanjula
 */
public class ticketbooking extends javax.swing.JFrame {

    /**
     * Creates new form ticketbooking
     */
    public ticketbooking() {
        initComponents();
        txtticketNumber.setText(generateTicketNumber());
        txtCost.setEditable(false);
        txtticketNumber.setEditable(false);
        fromcombobox.setSelectedIndex(-1);
        tocombobox.setSelectedIndex(-1);
      

     
    }
    
     
private String generateTicketNumber() {
    String latestTicketNumber = "P1"; // Default if no tickets are found

    // Connect to the database and fetch the latest ticket number
    String dbloc = "jdbc:mysql://localhost:3306/railpilot";
    String username = "root";

    try (Connection connection = DriverManager.getConnection(dbloc, username, "")) {
        String query = "SELECT MAX(PassengerTicket_Id) FROM Passenger";
        try (PreparedStatement preparedStatement = connection.prepareStatement(query)) {
            try (ResultSet resultSet = preparedStatement.executeQuery()) {
                if (resultSet.next()) {
                    String maxTicketNumber = resultSet.getString(1);
                    if (maxTicketNumber != null) {
                        int ticketNumber = Integer.parseInt(maxTicketNumber.substring(1));
                        latestTicketNumber = "P" + (ticketNumber + 1);
                    }
                }
            }
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Error connecting to the database: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

    return latestTicketNumber;
}

    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtticketNumber = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtCost = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txttelephone = new javax.swing.JTextField();
        panel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        panel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        fromcombobox = new javax.swing.JComboBox<>();
        tocombobox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(102, 204, 0));
        setMaximumSize(new java.awt.Dimension(671, 416));
        setMinimumSize(new java.awt.Dimension(671, 416));
        setResizable(false);
        setSize(new java.awt.Dimension(671, 416));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ticket Number:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 24));

        jLabel3.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, 24));

        jLabel4.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("From:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, 24));

        jLabel5.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("To:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, -1, 24));

        jLabel6.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cost:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, 24));

        jLabel7.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, 24));

        jLabel8.setFont(new java.awt.Font("Lucida Bright", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Telephone:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, 24));

        panel1.setBackground(new java.awt.Color(0, 255, 255));

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel2.setText("                 BACK");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 500, 220, 30));

        txtticketNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtticketNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtticketNumberActionPerformed(evt);
            }
        });
        getContentPane().add(txtticketNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 220, -1));

        txtname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 220, -1));

        txtCost.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostActionPerformed(evt);
            }
        });
        getContentPane().add(txtCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 220, -1));

        txtemail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 220, -1));

        txttelephone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txttelephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 220, -1));

        panel2.setBackground(new java.awt.Color(0, 255, 255));

        jLabel9.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel9.setText("          BOOK TICKET");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        getContentPane().add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 220, 30));

        panel3.setBackground(new java.awt.Color(0, 255, 255));
        panel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel3MouseEntered(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel10.setText("                CLEAR");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        getContentPane().add(panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 220, 30));

        fromcombobox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fromcombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anuradhapura", "Kandy", "Colombo", "Bambalapitiya", "Galle", "Matara" }));
        fromcombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromcomboboxActionPerformed(evt);
            }
        });
        getContentPane().add(fromcombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 220, -1));

        tocombobox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tocombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anuradhapura", "Kandy", "Colombo", "Bambalapitiya", "Galle", "Matara" }));
        tocombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tocomboboxActionPerformed(evt);
            }
        });
        getContentPane().add(tocombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, 220, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/railpilot/BOOK TRAIN (2).png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 550, 70));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/railpilot/Untitled design_1.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:
        resetColor(panel1);
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
        setColor(panel1);
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private boolean isValidEmail(String email) {
        // Regular expression for a valid email address
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
        Pattern pattern = Pattern.compile(emailRegex);
        Matcher matcher = pattern.matcher(email);
        return matcher.matches();
    }

    private boolean isValidTelephone(String telephone) {
        // Regular expression for a valid telephone number
        String telephoneRegex = "^\\d{10}$";
        Pattern pattern = Pattern.compile(telephoneRegex);
        Matcher matcher = pattern.matcher(telephone);
        return matcher.matches();
    }

    
    
    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        txtticketNumber.setText("");
        txtname.setText("");
        txtemail.setText("");
        txttelephone.setText("");
        txtCost.setText("");
        fromcombobox.setSelectedIndex(-1);
        tocombobox.setSelectedIndex(-1);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
         setColor(panel3);
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        // TODO add your handling code here:
         resetColor(panel3);
    }//GEN-LAST:event_jLabel10MouseExited

    private void txtticketNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtticketNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtticketNumberActionPerformed

    private void panel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel3MouseEntered
      // TODO add your handling code here:
    }//GEN-LAST:event_panel3MouseEntered

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostActionPerformed

    private void fromcomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromcomboboxActionPerformed
        tocombobox.setSelectedIndex(-1);
    }//GEN-LAST:event_fromcomboboxActionPerformed

    private void tocomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tocomboboxActionPerformed
       try {
        int cost = 0;

        int selectedIndex = fromcombobox.getSelectedIndex();
        int toselectedIndex = tocombobox.getSelectedIndex();

        // Check if an item is selected in the "From" combo box
        if (selectedIndex == 0) {
            if (toselectedIndex == 1)
                cost = 750;
            else if (toselectedIndex == 2)
                cost = 900;
            else if (toselectedIndex == 3)
                cost = 1150;
            else if (toselectedIndex == 4)
                cost = 1300;
            else if (toselectedIndex == 5)
                cost = 1500;

        } else if (selectedIndex == 1) {
            if (toselectedIndex == 0)
                cost = 750;
            else if (toselectedIndex == 2)
                cost = 900;
            else if (toselectedIndex == 3)
                cost = 1150;
            else if (toselectedIndex == 4)
                cost = 1300;
            else if (toselectedIndex == 5)
                cost = 1500;

        }
        else if (selectedIndex == 2) {
            if (toselectedIndex == 0)
                cost = 800;
            else if (toselectedIndex == 1)
                cost = 950;
            else if (toselectedIndex == 3)
                cost = 1200;
            else if (toselectedIndex == 4)
                cost = 1300;
            else if (toselectedIndex == 5)
                cost = 1400;
        }
        else if (selectedIndex == 3) {
            if (toselectedIndex == 0)
                cost = 850;
            else if (toselectedIndex == 1)
                cost = 1000;
            else if (toselectedIndex == 2)
                cost = 1250;
            else if (toselectedIndex == 4)
                cost = 1350;
            else if (toselectedIndex == 5)
                cost = 1450;

        } else if (selectedIndex == 4) {
            if (toselectedIndex == 0)
                cost = 900;
            else if (toselectedIndex == 1)
                cost = 1050;
            else if (toselectedIndex == 2)
                cost = 1300;
            else if (toselectedIndex == 3)
                cost = 1400;
            else if (toselectedIndex == 5)
                cost = 1500;
        }
        else if (selectedIndex == 5) {
            if (toselectedIndex == 0)
                cost = 950;
            else if (toselectedIndex == 1)
                cost = 1100;
            else if (toselectedIndex == 2)
                cost = 1350;
            else if (toselectedIndex == 3)
                cost = 1450;
            else if (toselectedIndex == 4)
                cost = 1550;
        }

        
        txtCost.setText(String.valueOf(cost));
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
       
       txtticketNumber.setText("");
        txtname.setText("");
        txtemail.setText("");
        txttelephone.setText("");
        txtCost.setText("");
        fromcombobox.setSelectedIndex(-1);
        tocombobox.setSelectedIndex(-1);

    }//GEN-LAST:event_tocomboboxActionPerformed

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        resetColor(panel2);
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        setColor(panel2);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        String ticketNumber = txtticketNumber.getText();
        String name = txtname.getText();
        String email = txtemail.getText();
        String telephone = txttelephone.getText();
        String cost = txtCost.getText();

        if (ticketNumber.isEmpty() || name.isEmpty() || email.isEmpty() || telephone.isEmpty() || cost.isEmpty()) {
            JOptionPane.showMessageDialog(null, "All fields must be filled", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!isValidEmail(email)) {
            JOptionPane.showMessageDialog(null, "Invalid email format", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!isValidTelephone(telephone)) {
            JOptionPane.showMessageDialog(null, "Invalid telephone number format", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String dbloc = "jdbc:mysql://localhost:3306/railpilot";
        String username = "root";

        try (Connection connection = DriverManager.getConnection(dbloc, username, "")) {
            String query = "INSERT INTO Passenger (PassengerTicket_Id, Passenger_Name, Departure, Destination, Cost, Email, Passenger_TP) VALUES (?, ?, ?, ?, ?, ?, ?)";
            try (PreparedStatement preparedStatement = connection.prepareStatement(query)) {
                preparedStatement.setString(1, ticketNumber);
                preparedStatement.setString(2, name);
                preparedStatement.setString(3, (String) fromcombobox.getSelectedItem()); // Get the selected text from "From" combo box
                preparedStatement.setString(4, (String) tocombobox.getSelectedItem());   // Get the selected text from "To" combo box
                preparedStatement.setInt(5, Integer.parseInt(cost));
                preparedStatement.setString(6, email);
                preparedStatement.setInt(7, Integer.parseInt(telephone));

                int rowsInserted = preparedStatement.executeUpdate();
                if (rowsInserted > 0) {
                    JOptionPane.showMessageDialog(null, "Ticket booked successfully");
                } else {
                    JOptionPane.showMessageDialog(null, "Failed to book ticket", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error connecting to the database: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

        String tiketNumberText = txtticketNumber.getText().substring(1);

        int previousTicketID =0;
        boolean success = false;

        try {
            previousTicketID = Integer.parseInt(tiketNumberText);
            success = true;
        } catch (NumberFormatException e) {
            // Handle the case where parsing fails
            e.printStackTrace();
        }

        // If the previous train ID could be parsed successfully, increment it
        if (success) {
            int nextTrainID = previousTicketID + 1;
            txtticketNumber.setText("P" + nextTrainID);
        } else {
            JOptionPane.showMessageDialog(null, "Something's wrong, please check again", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jLabel9MouseClicked

    
    
    public void setColor(JPanel p)
    {
        p.setBackground(new Color(0,206,209));
    }
        public void resetColor(JPanel pl)
    {
        pl.setBackground(new Color(0,255,255));
    }
    
        
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ticketbooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ticketbooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ticketbooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ticketbooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ticketbooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> fromcombobox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JComboBox<String> tocombobox;
    private javax.swing.JTextField txtCost;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txttelephone;
    private javax.swing.JTextField txtticketNumber;
    // End of variables declaration//GEN-END:variables
}
